<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FrontendTraining.Domain\FrontendTraining.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Todos\CreateTodo\" />
    </ItemGroup>

</Project>
